version: '2'
services:
    khalilblogangular1-app:
        image: khalilblogangular1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://khalilblogangular1-postgresql:5432/khalilblogAngular1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=khalilblogangular1-elasticsearch:9300
        ports:
            - 8080:8080
    khalilblogangular1-postgresql:
        extends:
            file: postgresql.yml
            service: khalilblogangular1-postgresql
    khalilblogangular1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: khalilblogangular1-elasticsearch
